/******************************************************************************
 * Copyright (C) 2026, Advanced Micro Devices, Inc.
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * @brief	Fully parallel LUT neuron layer. Generated by LUTNeuron_rtl.
 *****************************************************************************/

module $TOP_MODULE_NAME$(
(* X_INTERFACE_PARAMETER = "ASSOCIATED_BUSIF in0_V:out0_V, ASSOCIATED_RESET = ap_rst_n" *)
(* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 ap_clk CLK" *)
input	ap_clk,
(* X_INTERFACE_PARAMETER = "POLARITY ACTIVE_LOW" *)
input	ap_rst_n,

// -- AXIS input ------------------
output	in0_V_TREADY,
input	in0_V_TVALID,
input	[$IN_STREAM_BITS$-1:0] in0_V_TDATA,

// -- AXIS output ------------------
input	out0_V_TREADY,
output	out0_V_TVALID,
output	[$OUT_STREAM_BITS$-1:0] out0_V_TDATA
);

// handshake domain of the combinational LUT logic
wire	[$IN_STREAM_BITS$-1:0]	core_in_wide;
wire				core_vld;
wire				core_rdy;

// stream padding bits are ignored on the way in and tied to zero on the way out
wire	[$IN_BITS$-1:0]		core_in = core_in_wide[$IN_BITS$-1:0];
wire	[$OUT_BITS$-1:0]	core_out_raw;
wire	[$OUT_STREAM_BITS$-1:0]	core_out = core_out_raw;

// -- optional input register stage ------------------
$INPUT_STAGE$

// -- LUT evaluation ------------------
$LUT_LOGIC$

// -- optional output register stage ------------------
$OUTPUT_STAGE$

endmodule
